# Generated by Django 4.2.4 on 2023-08-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categotyType',
            new_name='categoryType',
        ),
    ]
