# Generated by Django 4.2.4 on 2023-09-26 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_remove_category_subscribers_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='postCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='newsapp.category'),
        ),
    ]
